### PR TITLE
[macOS] Fix clipboard setData not working when text or html is null.

### LINKED ISSUE #9: [macOS] RichClipboard.setData does not work if either text or html data is null.
**Actual Behavior:**

Below code doesn't work on macOS because one of the data is set to null.

Code: 

```dart
await RichClipboard.setData(RichClipboardData(text: 'Sample text', html: null));
```

If I set `html` to anything other than null, then it works.

e.g.
```dart
await RichClipboard.setData(RichClipboardData(text: 'Sample text', html: ''));
```

**Expected Behavior:** 
It should clear html data if I set it to be null.

### PR DESCRIPTION
**Pull request by BirjuVachhani**
FIxes #9

### CODE REVIEW

File: rich_clipboard_macos/macos/Classes/RichClipboardPlugin.swift [hunk 1]
```diff
@@ -71,7 +68,7 @@ public class RichClipboardPlugin: NSObject, FlutterPlugin {
         }
         return String(data: htmlData, encoding: String.Encoding.utf8)
     }
-
+
```
Comment (jmatth) [inline rich_clipboard_macos/macos/Classes/RichClipboardPlugin.swift]: Please also remove all this whitespace noise. I find [SwiftFormat for Xcode](https://github.com/nicklockwood/SwiftFormat#xcode-source-editor-extension) useful for this and formatting in general.

**Review by jmatth — CHANGES_REQUESTED** [review]
Well this is embarrassing. Thanks for catching it.

I somehow accounted for this case in the iOS version of this plugin but not macOS. I have a comment below suggesting we use that implementation instead. I can also handle the fix myself if you'd prefer not to go back and forth on a PR but I don't want to take those Gitub contribution stats from you.

File: rich_clipboard_macos/macos/Classes/RichClipboardPlugin.swift [hunk 2]
```diff
@@ -36,26 +36,23 @@ public class RichClipboardPlugin: NSObject, FlutterPlugin {
...
     }
-
+    
     func setData(_ arguments: Any?) {
-        guard let data = arguments as? [String: String] else {
-            return
-        }
-
-        guard let text = data[mimeTextPlain] else {
+        guard let data = arguments as? [String: String?] else {
```
Comment (jmatth) [inline rich_clipboard_macos/macos/Classes/RichClipboardPlugin.swift]: This comment was supposed to be in my previous review, but Github ate it or something.

Rather than account for `nil` everywhere this dictionary is accessed, we can just filter the `nil` values out here. This is already implemented in the iOS plugin:

```suggestion
        guard let data = (arguments as? [String: String?])?.filter({ $0.value != nil }) as? [String: String] else {
```

Alternatively, there's a way to do the same thing with less code and one less typecast using [`compactMapValues`][2]:

```suggestion
        guard let data = (arguments as? [String: String?])?.compactMapValues({ $0 }) else {
```

I'm good with either approach. If you go with the second option please also update [the matching line in the iOS plugin][2] so we're consistent across the Swift portions of the codebase.

[1]: https://github.com/BringingFire/rich_clipboard/blob/3ad6510f7bce215ea0f846450b5b35e1b1772678/rich_clipboard_ios/ios/Classes/RichClipboardPlugin.swift#L56
[2]: https://developer.apple.com/documentation/swift/dictionary/compactmapvalues(_:)

Comment (BirjuVachhani) [reply rich_clipboard_macos/macos/Classes/RichClipboardPlugin.swift]: @jmatth Thanks for the review. These are really good points. I'll update the code.

**Comment by BirjuVachhani** [comment]
@jmatth Updated.

**Review by jmatth — APPROVED** [review]

**Comment by jmatth** [comment]
Merged, thanks for the contribution. I'll push an update to pub.dev later today

**Comment by BirjuVachhani** [comment]
@jmatth When are you releasing this?

**Comment by jmatth** [comment]
I released it [last week][versions]. You should be able to update it in any existing projects with `flutter pub upgrade rich_clipboard_macos`. That worked in my testing, let me know if it's not showing up for you and I'll investigate.

[versions]: https://pub.dev/packages/rich_clipboard_macos/versions
